# use http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# cache local Maven repo: http://docs.travis-ci.com/user/caching/
cache:
  directories:
  - $HOME/.m2/repository

language: java

# Use the 'true' command to avoid up-front dependency fetching, for faster builds
# See http://docs.travis-ci.com/user/languages/java/#Dependency-Management
install: /bin/true

script: |
  mvn test site \
    --batch-mode \
    --settings .travis-settings.xml \
    -DstaticAnalysis

jdk:
  - openjdk7
  - oraclejdk7
# Enunciate 1.x doesn't support javac 1.8:
#  - oraclejdk8

matrix:
  fast_finish: true
